### PR TITLE
Changes to make reset-password-dialog work on Alfresco version 4.2.x 

### PR DESCRIPTION
**Pull request by billerby**
**Will,**
Since I'm not so familiar with the ant way of building Alfresco extensions I just tried to look through some source code to understand where to put what files. Hopefully this is correct. Please review and test it before merging. 

**This module needs to be deployed in the modules/deploy gui before it becomes functional.**

I figure you probably should put this on a separate branch (maybe I should have created the pull request from a topic branch as well...sorry in that case for not doing it...) so that the users of older Alfresco versions still can use the old version of the extension. Since I'm not familiar with how you version this stuff I did not elevate the version number, I'll leave that up to you.

### CODE REVIEW

**Comment by wabson** [comment]
Thanks, Erik! Are there also some web script customisation files for the `login.get` script? I see you are using a package `org.shareextras.components.guest` in the module but I don't see any resources in the pull request under that package.

**Comment by billerby** [comment]
Added the missing files and also spotted (and renamed) that the package name was sharextras and not shareextras...

**Comment by nks0ne** [comment]
it would be a good idea to point out the location of the management console in the readme.md:
http://{hostname}:{port}/share/service/modules/deploy.

**Comment by jovett** [comment]
I have installed the jar  file into 4.2c ,  and nothing shows up in the module deploy console after restart server?

**Comment by eemubertling** [comment]
I have 4.2.c and nothing shows up in deploy console.

**Pull request merged**
